<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30088" started-at="2019-03-25T04:17:50Z" finished-at="2019-03-25T04:18:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30088" started-at="2019-03-25T04:17:50Z" finished-at="2019-03-25T04:18:20Z">
      <class name="TestLogin">
        <test-method status="PASS" signature="setup()[pri:0, instance:TestLogin@78c730]" name="setup" is-config="true" duration-ms="3813" started-at="2019-03-25T04:17:50Z" finished-at="2019-03-25T04:17:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testLoginSuccessCase()[pri:0, instance:TestLogin@78c730]" name="testLoginSuccessCase" duration-ms="10640" started-at="2019-03-25T04:17:54Z" finished-at="2019-03-25T04:18:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginSuccessCase -->
        <test-method status="PASS" signature="clean()[pri:0, instance:TestLogin@78c730]" name="clean" is-config="true" duration-ms="1345" started-at="2019-03-25T04:18:04Z" finished-at="2019-03-25T04:18:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method status="PASS" signature="testLoginEmpty()[pri:1, instance:TestLogin@78c730]" name="testLoginEmpty" duration-ms="1820" started-at="2019-03-25T04:18:06Z" finished-at="2019-03-25T04:18:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginEmpty -->
        <test-method status="PASS" signature="clean()[pri:0, instance:TestLogin@78c730]" name="clean" is-config="true" duration-ms="5023" started-at="2019-03-25T04:18:07Z" finished-at="2019-03-25T04:18:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method status="FAIL" signature="testLoginBadAccount()[pri:2, instance:TestLogin@78c730]" name="testLoginBadAccount" duration-ms="1767" started-at="2019-03-25T04:18:12Z" finished-at="2019-03-25T04:18:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at TestLogin.testLoginBadAccount(TestLogin.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginBadAccount -->
        <test-method status="PASS" signature="clean()[pri:0, instance:TestLogin@78c730]" name="clean" is-config="true" duration-ms="5056" started-at="2019-03-25T04:18:14Z" finished-at="2019-03-25T04:18:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clean -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:TestLogin@78c730]" name="teardown" is-config="true" duration-ms="619" started-at="2019-03-25T04:18:19Z" finished-at="2019-03-25T04:18:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- TestLogin -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
